version: "3"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx_education
    working_dir: /project
    depends_on:
      - php_fpm
    volumes:
      - ./../api:/project
      - ./config/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/dev/logs/nginx/:/var/log/nginx/
    ports:
      - "80:80"

  php_fpm:
    image: webdevops/php-dev:8.3-alpine
    container_name: php_fpm_education
    working_dir: /project
    environment:
      XDEBUG_DISCOVER_CLIENT_HOST: "true"
      PHP_IDE_CONFIG: "serverName=education-fpm"
      # pusher/soketi configuration
#      BROADCAST_DRIVER: pusher
#      PUSHER_APP_ID: "app-id"
#      PUSHER_APP_KEY: "app-key"
#      PUSHER_APP_SECRET: "app-secret"
#      PUSHER_HOST: "soketi"
#      PUSHER_PORT: 6001
#      PUSHER_SCHEME: http
#
#      DB_CONNECTION: mysql
#      DB_HOST: mysql
#      DB_PORT: 3306
#      DB_DATABASE: papay
#      DB_USERNAME: root
#      DB_PASSWORD:
    depends_on:
      - mysql
      - redis
      - soketi
    volumes:
      - ./../api:/project
      - ./config/dev/php/php.ini:/opt/docker/etc/php/php.ini
      - ./config/dev/php/xdebug.ini:/opt/docker/etc/php/conf.d/xdebug.ini

  redis:
    image: redis:alpine
    container_name: redis_education
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_education_dev
    networks:
      - default
    environment:
      MYSQL_DATABASE: education
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

  mysql_phpunit:
    image: mysql:8.0
    restart: always
    container_name: mysql_phpunit_education
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3301:3306"

  soketi:
    image: quay.io/soketi/soketi:1.4-16-debian
    environment:
      SOKETI_DEBUG: 1
      SOKETI_DEFAULT_APP_ENABLE_CLIENT_MESSAGES: 'true'
    ports:
      - "6001:6001"
      - "9601:9601"

